version: "3"
services:    
    web1:
        build: ./ticTakTicket
        ports:
            -  "8443:8443"
        links:
            - db
            - api1
        networks:
            - my-new-net
        environment:
            - SERVER_PORT=8444
    api1:
        build: ./servicioInterno
        ports:
            -  "8080:8080"
        links:
            - db
        networks:
            - my-new-net
        environment:
            - SERVER_PORT=8080


    db: 
        image: mysql:5.6.48
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: 'tic_tak_ticket'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
            -  "3306:3306"
        networks:
            - my-new-net

networks:
     my-new-net:
        driver: bridge

      

